# Generated by Django 4.1.7 on 2023-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
