# Generated by Django 4.1.7 on 2023-05-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='owner',
            new_name='client',
        ),
    ]
